// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCPP.Core.Database;

#nullable disable

namespace OCPP.Core.Database.Migrations
{
    [DbContext(typeof(OCPPCoreContext))]
    [Migration("20251201211840_migration_20251201221837")]
    partial class migration_20251201221837
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCPP.Core.Database.ChargePaymentReservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ActualEnergyKwh")
                        .HasColumnType("float");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CapturedAmountCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChargeTagId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("MaxAmountCents")
                        .HasColumnType("bigint");

                    b.Property<double>("MaxEnergyKwh")
                        .HasColumnType("float");

                    b.Property<int>("MaxUsageFeeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StartUsageFeeAfterMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageFeeAnchorMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("UsageFeePerMinute")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UserSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ReservationId");

                    b.HasIndex("StripeCheckoutSessionId")
                        .HasDatabaseName("IX_PaymentReservations_StripeSession");

                    b.HasIndex("StripePaymentIntentId")
                        .HasDatabaseName("IX_PaymentReservations_PaymentIntent");

                    b.ToTable("ChargePaymentReservation", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientCertThumb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ConnectorUsageFeePerMinute")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("FreeChargingEnabled")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("MaxSessionKwh")
                        .HasColumnType("float");

                    b.Property<int>("MaxUsageFeeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("OwnerSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StartUsageFeeAfterMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("UsageFeeAfterChargingEnds")
                        .HasColumnType("bit");

                    b.Property<decimal>("UserSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChargePointId");

                    b.HasIndex("OwnerId");

                    b.HasIndex(new[] { "ChargePointId" }, "ChargePoint_Identifier")
                        .IsUnique();

                    b.ToTable("ChargePoint", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTag", b =>
                {
                    b.Property<string>("TagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Blocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentTagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TagId")
                        .HasName("PK_ChargeKeys");

                    b.ToTable("ChargeTags");
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("LastMeter")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastMeterTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastStatusTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ChargePointId", "ConnectorId");

                    b.ToTable("ConnectorStatus", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.MessageLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex(new[] { "LogTime" }, "IX_MessageLog_ChargePointId");

                    b.ToTable("MessageLog", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ChargingEndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("EnergyCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("EnergyKwh")
                        .HasColumnType("float");

                    b.Property<decimal>("IdleUsageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IdleUsageFeeMinutes")
                        .HasColumnType("int");

                    b.Property<double>("MeterStart")
                        .HasColumnType("float");

                    b.Property<double?>("MeterStop")
                        .HasColumnType("float");

                    b.Property<decimal>("OperatorCommissionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OperatorRevenueTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerPayoutTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerSessionFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StartResult")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartTagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StopTagId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UsageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UsageFeeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("UserSessionFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ChargePointId", "ConnectorId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.HasOne("OCPP.Core.Database.Owner", "Owner")
                        .WithMany("ChargePoints")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargePointId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_ChargePoint");

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OCPP.Core.Database.Owner", b =>
                {
                    b.Navigation("ChargePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
