// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OCPP.Core.Database.Migrations
{
    /// <inheritdoc />
    public partial class transaction_pricing_breakdown : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Currency",
                table: "Transaction",
                type: "nvarchar(10)",
                maxLength: 10,
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "EnergyCost",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<double>(
                name: "EnergyKwh",
                table: "Transaction",
                type: "float",
                nullable: false,
                defaultValue: 0.0);

            migrationBuilder.AddColumn<decimal>(
                name: "OperatorCommissionAmount",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OperatorRevenueTotal",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionFixedPerKwh",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionPercent",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerPayoutTotal",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerSessionFeeAmount",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "UsageFeeAmount",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "UsageFeeMinutes",
                table: "Transaction",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<decimal>(
                name: "UserSessionFeeAmount",
                table: "Transaction",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Currency",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "EnergyCost",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "EnergyKwh",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OperatorCommissionAmount",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OperatorRevenueTotal",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OwnerCommissionFixedPerKwh",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OwnerCommissionPercent",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OwnerPayoutTotal",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "OwnerSessionFeeAmount",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "UsageFeeAmount",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "UsageFeeMinutes",
                table: "Transaction");

            migrationBuilder.DropColumn(
                name: "UserSessionFeeAmount",
                table: "Transaction");
        }
    }
}
