// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OCPP.Core.Database.Migrations
{
    /// <inheritdoc />
    public partial class pricing_extensions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionFixedPerKwh",
                table: "ChargePoint",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionPercent",
                table: "ChargePoint",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "OwnerEmail",
                table: "ChargePoint",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "OwnerName",
                table: "ChargePoint",
                type: "nvarchar(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerSessionFee",
                table: "ChargePoint",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "UserSessionFee",
                table: "ChargePoint",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionFixedPerKwh",
                table: "ChargePaymentReservation",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerCommissionPercent",
                table: "ChargePaymentReservation",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OwnerSessionFee",
                table: "ChargePaymentReservation",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "UserSessionFee",
                table: "ChargePaymentReservation",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "OwnerCommissionFixedPerKwh",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "OwnerCommissionPercent",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "OwnerEmail",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "OwnerName",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "OwnerSessionFee",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "UserSessionFee",
                table: "ChargePoint");

            migrationBuilder.DropColumn(
                name: "OwnerCommissionFixedPerKwh",
                table: "ChargePaymentReservation");

            migrationBuilder.DropColumn(
                name: "OwnerCommissionPercent",
                table: "ChargePaymentReservation");

            migrationBuilder.DropColumn(
                name: "OwnerSessionFee",
                table: "ChargePaymentReservation");

            migrationBuilder.DropColumn(
                name: "UserSessionFee",
                table: "ChargePaymentReservation");
        }
    }
}
