// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCPP.Core.Database;

#nullable disable

namespace OCPP.Core.Database.Migrations
{
    [DbContext(typeof(OCPPCoreContext))]
    [Migration("20260309081142_AddPublicPortalSettings")]
    partial class AddPublicPortalSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("OCPP.Core.Database.ChargePaymentReservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveConnectorKey")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<double?>("ActualEnergyKwh")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AwaitingPlug")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CapturedAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargeTagId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOcppEventAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxEnergyKwh")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxUsageFeeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OcppIdTag")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("RemoteStartAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteStartResult")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteStartSentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDeadlineAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTransactionAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartUsageFeeAfterMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTransactionAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageFeeAnchorMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UsageFeePerMinute")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UserSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ReservationId");

                    b.HasIndex("StripeCheckoutSessionId")
                        .HasDatabaseName("IX_PaymentReservations_StripeSession");

                    b.HasIndex("StripePaymentIntentId")
                        .HasDatabaseName("IX_PaymentReservations_PaymentIntent");

                    b.HasIndex("ChargePointId", "ConnectorId", "ActiveConnectorKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentReservations_ActiveConnector");

                    b.HasIndex("ChargePointId", "ConnectorId", "OcppIdTag")
                        .HasDatabaseName("IX_PaymentReservations_CpConnTag");

                    b.ToTable("ChargePaymentReservation", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCertThumb")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConnectorUsageFeePerMinute")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FreeChargingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("MaxSessionKwh")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxUsageFeeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OwnerSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StartUsageFeeAfterMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsageFeeAfterChargingEnds")
                        .HasColumnType("bit");

                    b.Property<decimal>("UserSessionFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ChargePointId");

                    b.HasIndex("OwnerId");

                    b.HasIndex(new[] { "ChargePointId" }, "ChargePoint_Identifier")
                        .IsUnique();

                    b.ToTable("ChargePoint", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTag", b =>
                {
                    b.Property<string>("TagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Blocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TagId")
                        .HasName("PK_ChargeKeys");

                    b.ToTable("ChargeTags");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTagPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("FreeChargingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargePointId");

                    b.HasIndex("TagId", "ChargePointId")
                        .HasDatabaseName("IX_ChargeTagPrivilege_Tag_Point");

                    b.ToTable("ChargeTagPrivilege", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastMeter")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastMeterTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStatusTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ChargePointId", "ConnectorId");

                    b.ToTable("ConnectorStatus", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.InvoiceSubmissionLog", b =>
                {
                    b.Property<int>("InvoiceSubmissionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalDocumentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalInvoiceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPublicUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceKind")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOperation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderResponseStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceSubmissionLogId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_InvoiceSubmissionLog_Created");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_InvoiceSubmissionLog_Transaction");

                    b.HasIndex("ReservationId", "CreatedAtUtc")
                        .HasDatabaseName("IX_InvoiceSubmissionLog_Reservation_Created");

                    b.ToTable("InvoiceSubmissionLog", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.MessageLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex(new[] { "LogTime" }, "IX_MessageLog_ChargePointId");

                    b.ToTable("MessageLog", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.PublicPortalSettings", b =>
                {
                    b.Property<int>("PublicPortalSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("FooterAddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterCompanyLine")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterLegalLine")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HelpUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("QrScannerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("PublicPortalSettingsId");

                    b.ToTable("PublicPortalSettings", (string)null);
                });

            modelBuilder.Entity("OCPP.Core.Database.StripeWebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StripeCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("StripeWebhookEvents");
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChargingEndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EnergyCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("EnergyKwh")
                        .HasColumnType("REAL");

                    b.Property<string>("FreeReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IdleUsageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IdleUsageFeeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeterStart")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeterStop")
                        .HasColumnType("REAL");

                    b.Property<decimal>("OperatorCommissionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OperatorRevenueTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionFixedPerKwh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerCommissionPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerPayoutTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OwnerSessionFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StartResult")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopTagId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UsageFeeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UserSessionFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ChargePointId", "ConnectorId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.HasOne("OCPP.Core.Database.Owner", "Owner")
                        .WithMany("ChargePoints")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargeTagPrivilege", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OCPP.Core.Database.ChargeTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OCPP.Core.Database.ConnectorStatus", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany()
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.Transaction", b =>
                {
                    b.HasOne("OCPP.Core.Database.ChargePoint", "ChargePoint")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargePointId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_ChargePoint");

                    b.Navigation("ChargePoint");
                });

            modelBuilder.Entity("OCPP.Core.Database.ChargePoint", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OCPP.Core.Database.Owner", b =>
                {
                    b.Navigation("ChargePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
